### ISSUE TITLE
Feature Request - Add Container Name & Sort Alphabetically

### ISSUE THREAD

**Issue by samcro1967** [vergoh/vnstat-docker#11]
Appreciate you work on this project.  Wondering if it is possible to add the container name in front of the interface name and then sort them alphabetically.  I have multiple servers each with 50+ containers.  Saves the step of looking up the container interface name to find it in the UI.

**Comment by vergoh** [comment]
Setting a name in front of the interface name is possible with `--setalias`. I'm not sure if there's any good / generic api available that vnStat could access, especially if it's also running in a container, for figuring out which interface belongs to which container. I suspect writing a script for doing the mapping on the host and then executing the necessary `--setalias` commands could be one possibility.

However, there's currently no sorting option available based on the alias name as the sorting order will still default to using the interface name even when some alias is set. This part at least is something I'll have to improve on the vnStat side (https://github.com/vergoh/vnstat) directly as I suspect the same situation could be valid even without containers.

Side note: your timing with this request is interesting since as there's another request (#12) at the same wanting to filter out container specific interfaces.

**Comment by samcro1967** [comment]
Yeah, I haven't found an easy way to get from the interface name to a container name.  Going the other way is pretty straightforward, but it would require docker.sock mounted to the container and the docker cli in the container.   One could then loop through the containers and add them to the database.  But, it will increase the container size, exposes docker.sock to the container as a possible security vector to be exploited, adds another dependency to be updated, more processing to do each update cycle, etc.

```
num=$(docker exec -i sonarr cat /sys/class/net/eth0/iflink | tr -d '\r'); ip ad | grep -oE "^${num}: veth[^@]+" | awk '{print $2}'
```

**Comment by vergoh** [comment]
For docker networks (= `br-*` interfaces) this kind of solution could work (this outputs the necessary commands as example without executing):
```
docker network ls --format json | jq -r 'select( .Driver == "bridge" and .Labels != "") | "docker exec vnstat vnstat -i br-" + (.ID) + " --setalias " + (.Name)'
```
However, for container specific interfaces there doesn't appear to be anything in the `docker inspect` output that could be used for mapping the interfaces to container names. `ip netns list` is also a dead end as those that docker registers aren't directly visible to the `ip` command. Otherwise .NetworkSettings.SandboxKey in the `docker inspect` output could have been of some use

The closest I could find was  https://github.com/cslev/find_veth_docker that has an example how to do it with the assumption that all the running containers have at least the `ip` command (no docker.sock needed).

**Comment by samcro1967** [comment]
Cadvisor can display live network traffic per container.  It grabs the container name, but not the interface name.  It is not mounting docker.sock.  It mounts the volumes below.

```
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
```

**Comment by samcro1967** [comment]
Not elegant, but wouldn't be opposed to running a script via cron hourly/daily on the host to create a reference file in the folder mounted to /var/lib/vnstat.  Maybe aliases could automagically be set/updated based on interfaces.txt on each update interval?

<details>
<summary>interfaces.sh</summary>

```
#!/usr/bin/env bash
get_container_names() {
  docker container ls --format '{{ .Names }}'
}
get_container_iflink() {
  docker exec "$1" cat /sys/class/net/eth0/iflink
}
get_veth_interfaces() {
  find /sys/class/net -type l -name 'veth*'
}
get_interface_index() {
  cat "$1/ifindex"
}
find_veth_interface_with_matching_index() {
  for interface in $(get_veth_interfaces); do
    if [ $(get_interface_index "$interface") = "$1" ]; then
      echo "${interface##*/}"
      break
    fi
  done
}
rm interfaces.txt
touch interfaces.txt
for container in $(get_container_names); do
  iflink=$(get_container_iflink "$container")
  network=$(find_veth_interface_with_matching_index "$iflink")
  if [ "$network" ]; then
    echo "$container - $network" >> interfaces.txt
  fi
done
sort interfaces.txt
```
</details>

**Comment by vergoh** [comment]
Support for changing the interface order from interface name to interface alias using the INTERFACE_ORDER environment variable (see README.md) is now included in the latest `:dev` tagged image. `:latest` will gain this functionality once verson 2.11 is released.

Adding support for custom interfaces.txt however isn't something I plan on implementing. That script you wrote can as well call `vnstat --setalias` via the correct container directly so there shouldn't be any need for an intermediate layer for moving that information around.
