### ISSUE TITLE
Push images to a different registry

### ISSUE THREAD

**Issue by onedr0p** [vergoh/vnstat-docker#13]
Given the recent dockerhub announcement of removing free team orgs, I'm wondering if the current org will be affected? And if so perhaps this could have a high priority? There are other options to use like GHCR or Quay.

https://github.com/docker/hub-feedback/issues/2314

**Comment by vergoh** [comment]
The images in https://hub.docker.com/r/vergoh/vnstat are currently under my "Docker Personal" account and not linked to any organization. As a result, those aren't affected by the announcement I too did notice mentioned in several places but which wasn't sent to me directly from Docker. It also looks like Dockers is now in the process of trying to at least recover from some of the damage that the announcement did cause: https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/

In any case, I have the option of pushing the images also to GHCR on my todo list as it wouldn't hurt to have alternatives, especially since the rate limits in Docker Hub may be a restriction to some.

**Comment by onedr0p** [comment]
@vergoh PR created https://github.com/vergoh/vnstat-docker/pull/14

**Comment by vergoh** [comment]
Images for previous releases have now also been mirrored from Docker Hub to GHCR resulting in both registries having the same tags available.

**Comment by onedr0p** [comment]
Thank you @vergoh !
