### ISSUE TITLE
Access interface specific pages directly with URL path

### ISSUE THREAD

**Issue by wc7086** [vergoh/vnstat-docker#2]
I have multiple servers. When I want to concentrate all the network cards that need attention in a domain name, the current directory structure makes me wonder how to use Nginx for reverse proxy. There may be a way to do a reverse proxy, but that should be more troublesome.

**Comment by vergoh** [comment]
I haven't used the reverse proxy feature in Nginx, mainly only with Apache and Traefik, but looking at the documentation ( https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/ ) it does support having subdirectories mapped for the proxy. Considering this sort of setup:

- www.domain
- hostA.domain
- hostB.domain

It should be possible to configure Nginx to serve the stats from hostA.domain using the path https://www.domain/hostA/ and hostB.domain using https://www.domain/hostB/, if that's what you were looking for. Additionally in such case, I'd probably also manually create https://www.domain/vnstat/ (or something like that) which would pull the summary (`?0-s` for the cgi) or horizontal summary (`?0-hs` for the cgi) images for the relevant hosts/interfaces to one page as links to the /hostX/ paths.

**Comment by wc7086** [comment]
Sorry, because my English is not good, it often causes some expression problems. I think it is necessary to set up a directory for each network interface so that I can set the reverse proxy path for a specific network interface. For example, the name of the network interface is `eth0`, and the URL path is represented by `/eth0`. In this way, when I reverse proxy to the web interface page of the network interface, I don't need to care about the reverse proxy of the image.

**Comment by vergoh** [comment]
After some experimentation, it looks like I can get it working so that you can use the cgi script as part of the path, pad it with something if necessary and then finally follow with the interface name you'd want to be visible.

Right now the url is either `/` or `/index.cgi`. After the change it would allow also `/index.cgi/eth0` or even `/index.cgi/some/path/which/does/not/matter/eth0` for getting the interface specific page of eth0. The last part of the path is used for selecting the interface if something is given as path parameter for the cgi. However, using only `/some/path/which/does/not/matter/eth0` without `index.cgi` being part of the path isn't going to be supported as it would require changed to the httpd setup.
